name    'loispuig-dotdeb'
version '0.1.0'
source 'git://github.com/loispuig/puppet-dotdeb.git'
author 'Loïs PUIG'
license 'MIT'
summary 'Setup dotdeb repository on Debian OS'
description ''
project_page 'https://github.com/loispuig/puppet-dotdeb'
dependency 'puppetlabs/apt', '>= 2.2.2'
